POST https://api-node-do-zero.onrender.com/videos
Content-type: application/json

{
  "title": "Video Primeiro",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET https://api-node-do-zero.onrender.com/videos

###

PUT https://api-node-do-zero.onrender.com/videos/1901f6fd-4b84-4232-8ece-fbbe54fefc9a
Content-type: application/json

{
  "title": "Video Title vaaai",
  "description": "Esse é o segundo vídeo",
  "duration": 180
}

###

DELETE https://api-node-do-zero.onrender.com/videos/83f0d92d-13c8-4c86-b89a-c8bcb40bc639
